sudo: required
language: generic 
services:
  - docker

before_install:
  - docker build -t georgefinnpersonal/pokedock-client -f './client/Dockerfile' './client'

script:
- docker run -e CI=true georgefinnpersonal/pokedock-client npm run test
